apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - synology-csi-driver.yaml
  - synology-csi-node.yaml
  - synology-csi-controller.yaml
  - synology-csi-snapshotter.yaml
  - client-info-secret.yaml
  - storage-class-retain.yaml
  - synology-csi-controller-role.yaml
  - synology-csi-controller-rolebind.yaml
  - synology-csi-node-role.yaml
  - synology-csi-node-rolebind.yaml
  - synology-csi-sa.yaml
  - synology-csi-snapshotter-role.yaml
  - synology-csi-snapshotter-rolebind.yaml
