apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"csi-controller-sa","namespace":"synology-csi"}}
    name: csi-controller-sa
    namespace: synology-csi
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"csi-node-sa","namespace":"synology-csi"}}
    name: csi-node-sa
    namespace: synology-csi
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"csi-snapshotter-sa","namespace":"synology-csi"}}
    name: csi-snapshotter-sa
    namespace: synology-csi
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: default
    namespace: synology-csi
kind: List
metadata:
  resourceVersion: ""
