apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: 5.42.0 # Use latest stable from https://github.com/grafana/helm-charts/tree/main/charts/loki
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    mode: monolithic
    persistence:
      enabled: true
      size: 10Gi
    config:
      schema_config:
        configs:
          - from: 2023-01-01
            store: boltdb-shipper
            object_store: filesystem
            schema: v13
            index:
              prefix: index_
              period: 24h
      storage_config:
        boltdb_shipper:
          active_index_directory: /var/loki/index
          shared_store: filesystem
        filesystem:
          directory: /var/loki/chunks
    serviceMonitor:
      enabled: true

