apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-loki-grafana
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: kube-loki-grafana
      version: "5.x.x" #Could use 66.x, and flux will only update based upon the major version. 66.* works too. 
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      interval: 12h
  values:
    persistence:
      enabled: true
      size: 10Gi
      storageClassName: "standard"
     # ingress:
        #enabled: true
        #ingressClassName: traefik
       # hosts:
         # - grs.crpruett.net
        #tls: []
