apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: loki
  namespace: monitoring
spec:
  interval: 24h
  url: https://github.com/grafana/loki/tree/main/production/helm/loki
