apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-syn-data
  namespace: mealie
spec: 
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: synology-iscsi-retain
