apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system

spec:
  releasename: cilium
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.16.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system

  valeusFrom:
    - kind: Configmap
      name: cilium-values
