apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/mealie
images: 
  - name: ghcr.io/mealie-recipes/mealie
    newTag: v3.17.0
patches:
  - target:
      kind: PersistentVolumeClaim
      name: mealie-syn-data
      namespace: mealie
    patch: |-
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: mealie-syn-data
      spec: 
        storageClassName: synology-iscsi-retain
      resources:
        storage: 5Gi
  - target:
      kind: Deployment
      name: mealie
      namespace: mealie
    patch: |-
      apiVersion: v1
      kind: Deployment
      metadata:
        name: mealie
      spec:
        replicas: 1
        template:
          spec:
            volumes:
              - name: mealie-data
                persistentVolumeClaim:
                  claimName: mealie-syn-data    
